### ISSUE TITLE
Error on Docker-compose up 

### ISSUE THREAD

**Issue by clefavelli** [LERUfic/codeigniter-docker#1]
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/george/codeignite/codeigniter-docker/docker/mysql/data

**Comment by LERUfic** [comment]
@clefavelli I think this is happening because you are using  docker-compose v2
https://github.com/docker/docker.github.io/issues/4709#issuecomment-922831435

you can try to disable docker-compose v2 using this command
`docker-compose disable-v2`

**Comment by marcelmanz** [comment]
Does `docker-compose disable-v2` return anything?
